# Generated by Django 5.0.4 on 2024-04-09 14:26

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nextgenuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'Пользователь с таким именем уже сущестует'}, help_text='Не более 50 знаков. Буквы, цифры и @/./+/-/_', max_length=50, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()]),
        ),
    ]
