# Generated by Django 5.0.4 on 2024-04-09 22:26

import apps.services.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_remove_userprofile_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='images/avatars/default.png', max_length=1000, upload_to=apps.services.utils.file_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'jpeg'))]),
        ),
    ]
