# Generated by Django 5.0.4 on 2024-04-19 11:28

import apps.services.utils
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nextgenuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'Пользователь с таким именем уже сущестует'}, help_text='Не более 50 знаков. Буквы, цифры и @/./+/-/_', max_length=50, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='Юзернейм'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='images/default_user.jpg', max_length=1000, upload_to=apps.services.utils.file_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'jpeg'))], verbose_name='Аватар'),
        ),
    ]
