# Generated by Django 5.0.4 on 2024-04-19 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0007_alter_nextgenuser_username_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(max_length=255, verbose_name='URL'),
        ),
    ]
