name: blog-nextgen-prod

services:

  blog_backend:
    container_name: blog_backend
    build: ./django_app/
    restart: always
    command: sh /blog_nextgen/startup.sh
    env_file: .env
    depends_on:
      - db
    volumes:
      - static-data:/backend_static
      - media-data:/blog_nextgen/media

  nginx:
    container_name: nginx_blog
    build: ./nginx
    restart: always
    ports:
      - 8000:80
    volumes:
      - static-data:/blog_nextgen/static
      - media-data:/blog_nextgen/media
    depends_on:
      - blog_backend

  db:
    container_name: postgres_blog
    image: postgres:15
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file: .env


volumes:
  postgres-data:
  static-data:
  media-data:
