name: blog-nextgen-dev

services:

  blog_backend:
    container_name: blog_backend
    build: ./django_app/
    command: gunicorn blog_nextgen.wsgi:application --bind 0.0.0.0:8000
    env_file: .env
    depends_on:
      - db
    volumes:
      - static-data:/blog_nextgen/static
      - media-data:/blog_nextgen/media

  nginx:
    container_name: nginx_blog
    build: ./nginx/
    ports:
      - 8000:80
    depends_on:
      - blog_backend
    volumes:
      - static-data:/blog_nextgen/static
      - media-data:/blog_nextgen/media

  db:
    container_name: postgres_blog
    image: postgres:15
    env_file: .env
    volumes:
      - postgres-data:/data/postgres-data


volumes:
  postgres-data:
  static-data:
  media-data:
