name: blog-nextgen-prod

services:

  blog_backend:
    container_name: blog_backend
    build: ./django_app/
    restart: always
    command: sh /blog_nextgen/startup.sh
    env_file: .env
    depends_on:
      - db
    volumes:
      - static-data:/backend_static
      - media-data:/blog_nextgen/media

  nginx:
    container_name: nginx_blog
    build: ./nginx
    restart: always
    ports:
      - 8000:80
    volumes:
      - static-data:/blog_nextgen/static
      - media-data:/blog_nextgen/media
    depends_on:
      - blog_backend

  db:
    container_name: postgres_blog
    image: postgres:15
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file: .env

  celery:
    container_name: celery_blog
    build: ./django_app/
    env_file: .env
    command: sh /blog_nextgen/selery_startup.sh
    depends_on:
      - redis
      - db
      - blog_backend
    volumes:
      - .:/app

  redis:
    container_name: redis_blog
    image: redis:7.4.0
    expose:
      - 6379
    volumes:
      - redis-data:/data


volumes:
  postgres-data:
  static-data:
  media-data:
  redis-data:
