# Generated by Django 5.0.4 on 2024-04-20 19:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_postraiting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostRaiting',
            new_name='PostRating',
        ),
        migrations.RenameIndex(
            model_name='postrating',
            new_name='blog_postra_value_bed216_idx',
            old_name='blog_postra_value_5ebc0d_idx',
        ),
    ]
